export enum exceptionMessages  {
  PARKING_LOT_HAS_NO_SPACE = 'PARKING_LOT_HAS_NO_SPACE',
  PARKING_LOT_HAS_NO_THIS_CAR = 'PARKING_LOT_HAS_NO_THIS_CAR',
  PARKING_BOY_HAS_NO_SPACED_PARKING_LOT = 'PARKING_BOY_HAS_NO_SPACED_PARKING_LOT',
  PARKING_MANAGER_PARK_FAIL = 'PARKING_MANAGER_PARK_FAIL',
  PARKING_MANAGER_PICK_FAIL = 'PARKING_MANAGER_PICK_FAIL',
}
